// Auto-generated by generate_website_data.py
// Updated: 2026-04-22 16:48

window.EXCOM_PASSWORD = 'Narrators@2025';

window.CLUB_DATA = {
  "club_name": "Narrator's Club",
  "generated_at": "22 Apr 2026, 16:48",
  "members": [
    {
      "name": "Aayush Alok",
      "pathway": "Enrolled (pathway TBD)",
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Abhishek Dixit",
      "pathway": "Leadership Development",
      "pathway_color": "#b45309",
      "completed_levels": 2,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Leadership Style",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "current",
          "projects": [
            "Planning and Implementing",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Leading Your Team",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Lead in Any Situation",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Aditi Kumari",
      "pathway": "Effective Coaching",
      "pathway_color": "#2563eb",
      "completed_levels": 4,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Communication Style",
            "Active Listening",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Successful Collaboration",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "complete",
          "projects": [
            "Motivate Others",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "current",
          "projects": [
            "Lead in Any Situation",
            "Reflect on Your Path",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Akash Yadav",
      "pathway": "Engaging Humor",
      "pathway_color": "#ea580c",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Connect with Your Audience",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Engage Your Audience With Humor",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "The Power of Humor in an Impromptu Speech",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Deliver Your Message with Humor",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Ananda Ragavan",
      "pathway": "Enrolled (pathway TBD)",
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Devi Shankar Jha",
      "pathway": "Team Collaboration",
      "pathway_color": "#0891b2",
      "completed_levels": 3,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Leadership Style",
            "Active Listening",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Successful Collaboration",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "current",
          "projects": [
            "Motivate Others",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Lead in Any Situation",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Dumpa Venkata Sai Jagadeesh",
      "pathway": "Leadership Development",
      "pathway_color": "#b45309",
      "completed_levels": 3,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Leadership Style",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Planning and Implementing",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "current",
          "projects": [
            "Leading Your Team",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Lead in Any Situation",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Karthik Arasaiah",
      "pathway": null,
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": true,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": "Sudhanshu Barthwal",
      "levels": []
    },
    {
      "name": "Lakshmi Satya Sai Sindhu Karri",
      "pathway": "Presentation Mastery",
      "pathway_color": "#7c3aed",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": "Club President",
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Writing a Speech with Purpose",
            "Introduction to Vocal Variety and Body Language",
            "Evaluation and Feedback",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Understanding Your Communication Style",
            "Effective Body Language",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Persuasive Speaking",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Managing a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Prepare to Speak Professionally",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Lipsa Chhotray",
      "pathway": "Innovative Planning",
      "pathway_color": "#16a34a",
      "completed_levels": 3,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Leadership Style",
            "Connect with Your Audience",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Present a Proposal",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "current",
          "projects": [
            "Manage a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Lead in Any Situation",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Mahabir Singh Bisht",
      "pathway": "Presentation Mastery",
      "pathway_color": "#7c3aed",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": "Club Secretary",
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Writing a Speech with Purpose",
            "Introduction to Vocal Variety and Body Language",
            "Evaluation and Feedback",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Understanding Your Communication Style",
            "Effective Body Language",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Persuasive Speaking",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Managing a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Prepare to Speak Professionally",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Mohammed Salick Shafi",
      "pathway": null,
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": true,
      "excom_role": null,
      "pay_norm": "pending",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Nemichandra B N",
      "pathway": "Dynamic Leadership",
      "pathway_color": "#dc2626",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": "VP Membership",
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Understanding Your Leadership Style",
            "Active Listening",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Negotiate the Best Outcome",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Manage Change",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Lead in Any Situation",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Nikhil Pillai",
      "pathway": "Enrolled (pathway TBD)",
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Nithya Ragothaman",
      "pathway": null,
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": true,
      "excom_role": null,
      "pay_norm": "pending",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Prathik Shetty",
      "pathway": "Distinguished Toastmaster",
      "pathway_color": "#6b7280",
      "completed_levels": 99,
      "total_levels": 5,
      "is_dtm": true,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Roopa V. G",
      "pathway": "Engaging Humor",
      "pathway_color": "#ea580c",
      "completed_levels": 4,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Evaluation and Feedback",
            "Researching and Presenting",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Connect with Your Audience",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Engage Your Audience With Humor",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "complete",
          "projects": [
            "The Power of Humor in an Impromptu Speech",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "current",
          "projects": [
            "Deliver Your Message with Humor",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Sahil Aggarwal",
      "pathway": null,
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": true,
      "excom_role": "Club Treasurer",
      "pay_norm": "unpaid",
      "mentor": "Sudhanshu Barthwal",
      "levels": []
    },
    {
      "name": "Sanjay Thillaivasan",
      "pathway": null,
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": true,
      "excom_role": null,
      "pay_norm": "pending",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Sheetal Avula",
      "pathway": "Presentation Mastery",
      "pathway_color": "#7c3aed",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": "VP Education",
      "pay_norm": "paid",
      "mentor": "Devi Shankar Jha",
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Writing a Speech with Purpose",
            "Introduction to Vocal Variety and Body Language",
            "Evaluation and Feedback",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Understanding Your Communication Style",
            "Effective Body Language",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Persuasive Speaking",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Managing a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Prepare to Speak Professionally",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Shuddhatm Choudhary",
      "pathway": "Enrolled (pathway TBD)",
      "pathway_color": "#6b7280",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "unpaid",
      "mentor": null,
      "levels": []
    },
    {
      "name": "Sudhanshu Barthwal",
      "pathway": "Presentation Mastery",
      "pathway_color": "#7c3aed",
      "completed_levels": 3,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": null,
      "pay_norm": "paid",
      "mentor": null,
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "complete",
          "projects": [
            "Ice Breaker",
            "Writing a Speech with Purpose",
            "Introduction to Vocal Variety and Body Language",
            "Evaluation and Feedback",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "complete",
          "projects": [
            "Understanding Your Communication Style",
            "Effective Body Language",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "complete",
          "projects": [
            "Persuasive Speaking",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "current",
          "projects": [
            "Managing a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Prepare to Speak Professionally",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    },
    {
      "name": "Yamuna J K",
      "pathway": "Presentation Mastery",
      "pathway_color": "#7c3aed",
      "completed_levels": 0,
      "total_levels": 5,
      "is_dtm": false,
      "not_enrolled": false,
      "excom_role": "VP PR",
      "pay_norm": "paid",
      "mentor": "Dumpa Venkata Sai Jagadeesh",
      "levels": [
        {
          "level": 1,
          "title": "Mastering Fundamentals",
          "status": "current",
          "projects": [
            "Ice Breaker",
            "Writing a Speech with Purpose",
            "Introduction to Vocal Variety and Body Language",
            "Evaluation and Feedback",
            "Level 1 Completion"
          ]
        },
        {
          "level": 2,
          "title": "Learning Your Style",
          "status": "future",
          "projects": [
            "Understanding Your Communication Style",
            "Effective Body Language",
            "Introduction to Toastmasters Mentoring",
            "Level 2 Completion"
          ]
        },
        {
          "level": 3,
          "title": "Increasing Knowledge",
          "status": "future",
          "projects": [
            "Persuasive Speaking",
            "+ 1 Elective project (your choice)",
            "Level 3 Completion"
          ]
        },
        {
          "level": 4,
          "title": "Building Skills",
          "status": "future",
          "projects": [
            "Managing a Difficult Audience",
            "+ 1 Elective project (your choice)",
            "Level 4 Completion"
          ]
        },
        {
          "level": 5,
          "title": "Demonstrating Expertise",
          "status": "future",
          "projects": [
            "Prepare to Speak Professionally",
            "+ 1 Elective project (your choice)",
            "Level 5 Completion"
          ]
        }
      ]
    }
  ]
};

window.MEMBERSHIP_DATA = [
  {
    "name": "Aayush Alok",
    "pid": "PN-67921724",
    "member_since": "August 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Enrolled (pathway TBD)"
  },
  {
    "name": "Abhishek Dixit",
    "pid": "PN-07892591",
    "member_since": "July 01, 2021",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Leadership Development"
  },
  {
    "name": "Ananda Ragavan",
    "pid": "PN-67921003",
    "member_since": "August 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Enrolled (pathway TBD)"
  },
  {
    "name": "Dumpa Venkata Sai Jagadeesh",
    "pid": "PN-67514023",
    "member_since": "September 01, 2022",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Leadership Development"
  },
  {
    "name": "Karthik Arasaiah",
    "pid": "PN-67904615",
    "member_since": "July 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Not Enrolled"
  },
  {
    "name": "Lipsa Chhotray",
    "pid": "PN-07938873",
    "member_since": "October 01, 2021",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Innovative Planning"
  },
  {
    "name": "Nikhil Pillai",
    "pid": "PN-67915992",
    "member_since": "July 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Enrolled (pathway TBD)"
  },
  {
    "name": "Prathik Shetty",
    "pid": "PN-06642406",
    "member_since": "August 01, 2017",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Distinguished Toastmaster"
  },
  {
    "name": "Sahil Aggarwal",
    "pid": "PN-67896290",
    "member_since": "June 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": "Club Treasurer",
    "pathway": "Not Enrolled"
  },
  {
    "name": "Shuddhatm Choudhary",
    "pid": "PN-67892489",
    "member_since": "June 01, 2025",
    "pay_status": "Unpaid",
    "pay_date": "March 31, 2026",
    "pay_norm": "unpaid",
    "excom_role": null,
    "pathway": "Enrolled (pathway TBD)"
  },
  {
    "name": "Mohammed Salick Shafi",
    "pid": "PN-67998280",
    "member_since": "",
    "pay_status": "Membership Pending",
    "pay_date": "",
    "pay_norm": "pending",
    "excom_role": null,
    "pathway": "Not Enrolled"
  },
  {
    "name": "Nithya Ragothaman",
    "pid": "PN-68046803",
    "member_since": "",
    "pay_status": "Membership Pending",
    "pay_date": "",
    "pay_norm": "pending",
    "excom_role": null,
    "pathway": "Not Enrolled"
  },
  {
    "name": "Sanjay Thillaivasan",
    "pid": "PN-68066088",
    "member_since": "",
    "pay_status": "Membership Pending",
    "pay_date": "",
    "pay_norm": "pending",
    "excom_role": null,
    "pathway": "Not Enrolled"
  },
  {
    "name": "Aditi Kumari",
    "pid": "PN-67619504",
    "member_since": "July 01, 2023",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": null,
    "pathway": "Effective Coaching"
  },
  {
    "name": "Akash Yadav",
    "pid": "PN-07876555",
    "member_since": "April 01, 2021",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": null,
    "pathway": "Engaging Humor"
  },
  {
    "name": "Devi Shankar Jha",
    "pid": "PN-67508007",
    "member_since": "August 01, 2022",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": null,
    "pathway": "Team Collaboration"
  },
  {
    "name": "Lakshmi Satya Sai Sindhu Karri",
    "pid": "PN-67816019",
    "member_since": "February 01, 2025",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": "Club President",
    "pathway": "Presentation Mastery"
  },
  {
    "name": "Mahabir Singh Bisht",
    "pid": "PN-67914496",
    "member_since": "July 01, 2025",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": "Club Secretary",
    "pathway": "Presentation Mastery"
  },
  {
    "name": "Nemichandra B N",
    "pid": "PN-67859626",
    "member_since": "April 01, 2025",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": "VP Membership",
    "pathway": "Dynamic Leadership"
  },
  {
    "name": "Roopa V. G",
    "pid": "PN-07137403",
    "member_since": "October 01, 2018",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": null,
    "pathway": "Engaging Humor"
  },
  {
    "name": "Sheetal Avula",
    "pid": "PN-67909334",
    "member_since": "June 01, 2025",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": "VP Education",
    "pathway": "Presentation Mastery"
  },
  {
    "name": "Sudhanshu Barthwal",
    "pid": "PN-07959243",
    "member_since": "December 01, 2021",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": null,
    "pathway": "Presentation Mastery"
  },
  {
    "name": "Yamuna J K",
    "pid": "PN-67904643",
    "member_since": "June 01, 2025",
    "pay_status": "Paid Until",
    "pay_date": "September 30, 2026",
    "pay_norm": "paid",
    "excom_role": "VP PR",
    "pathway": "Presentation Mastery"
  }
];

window.PATHWAY_STRUCTURES = {
  "Presentation Mastery": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Writing a Speech with Purpose",
        "Introduction to Vocal Variety and Body Language",
        "Evaluation and Feedback"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Communication Style",
        "Effective Body Language",
        "Introduction to Toastmasters Mentoring"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Persuasive Speaking"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Managing a Difficult Audience"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Prepare to Speak Professionally"
      ],
      "elective_count": 1
    }
  },
  "Effective Coaching": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Communication Style",
        "Active Listening",
        "Introduction to Toastmasters Mentoring"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Successful Collaboration"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Motivate Others"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Lead in Any Situation",
        "Reflect on Your Path"
      ],
      "elective_count": 1
    }
  },
  "Team Collaboration": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Leadership Style",
        "Active Listening"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Successful Collaboration"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Motivate Others"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Lead in Any Situation"
      ],
      "elective_count": 1
    }
  },
  "Dynamic Leadership": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Leadership Style",
        "Active Listening"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Negotiate the Best Outcome"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Manage Change"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Lead in Any Situation"
      ],
      "elective_count": 1
    }
  },
  "Leadership Development": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Leadership Style",
        "Introduction to Toastmasters Mentoring"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Planning and Implementing"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Leading Your Team"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Lead in Any Situation"
      ],
      "elective_count": 1
    }
  },
  "Innovative Planning": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Understanding Your Leadership Style",
        "Connect with Your Audience"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Present a Proposal"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "Manage a Difficult Audience"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Lead in Any Situation"
      ],
      "elective_count": 1
    }
  },
  "Engaging Humor": {
    "1": {
      "title": "Mastering Fundamentals",
      "required": [
        "Ice Breaker",
        "Evaluation and Feedback",
        "Researching and Presenting"
      ],
      "elective_count": 0
    },
    "2": {
      "title": "Learning Your Style",
      "required": [
        "Connect with Your Audience",
        "Introduction to Toastmasters Mentoring"
      ],
      "elective_count": 0
    },
    "3": {
      "title": "Increasing Knowledge",
      "required": [
        "Engage Your Audience With Humor"
      ],
      "elective_count": 1
    },
    "4": {
      "title": "Building Skills",
      "required": [
        "The Power of Humor in an Impromptu Speech"
      ],
      "elective_count": 1
    },
    "5": {
      "title": "Demonstrating Expertise",
      "required": [
        "Deliver Your Message with Humor"
      ],
      "elective_count": 1
    }
  }
};

window.PROJECT_COMPLETION_SEED = {
  "Lakshmi Satya Sai Sindhu Karri": {
    "Writing a Speech with Purpose": true,
    "Ice Breaker": true
  },
  "Karthik Arasaiah": {
    "Ice Breaker": true
  },
  "Mahabir Singh Bisht": {
    "Ice Breaker": true
  },
  "Sheetal Avula": {
    "Ice Breaker": true
  },
  "Sudhanshu Barthwal": {
    "Ice Breaker": true
  },
  "Yamuna J K": {
    "Ice Breaker": true
  }
};